import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'

import type { Metadata } from 'next'

import './globals.css'
import ProfilePic from '@/components/ProfilePic'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-800`}>
        <Navbar />
        <ProfilePic />

        {children}
      </body>
    </html>
  )
}
